# Generated by Django 5.2.3 on 2025-06-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('finder', 'finder'), ('claimant', 'Claimant')], default='claimant', max_length=10),
        ),
    ]
