# Generated by Django 5.2.3 on 2025-07-08 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_remove_verificationquestionnaire_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='verification.verificationquestion'),
        ),
    ]
