# Generated by Django 5.2.3 on 2025-07-08 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_image_url_item_item_image'),
        ('verification', '0003_alter_verificationanswer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lost_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='inventory.useritem')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='verification.verificationquestion')),
            ],
        ),
        migrations.DeleteModel(
            name='VerificationAnswer',
        ),
    ]
