# Generated by Django 5.2.3 on 2025-07-08 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_image_url_item_item_image'),
        ('verification', '0004_verificationanswers_delete_verificationanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationanswers',
            name='lost_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='inventory.useritem'),
        ),
    ]
