# Generated by Django 5.2.3 on 2025-07-08 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_alter_verificationanswers_lost_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationquestion',
            old_name='text',
            new_name='question_text',
        ),
    ]
