# Generated by Django 5.2.3 on 2025-07-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0006_rename_text_verificationquestion_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationanswers',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
