# Generated by Django 5.2.3 on 2025-07-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0007_verificationanswers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationanswers',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
