# Generated by Django 5.2.3 on 2025-07-10 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_image_url_item_item_image'),
        ('verification', '0008_alter_verificationanswers_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationanswers',
            name='lost_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_item_answers', to='inventory.useritem'),
        ),
        migrations.AlterField(
            model_name='verificationanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='verification.verificationquestion'),
        ),
    ]
