# Generated by Django 5.2.3 on 2025-06-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
