# Generated by Django 5.2.3 on 2025-07-07 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_remove_item_image_url_item_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_item_matches', to='inventory.useritem')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_item_matches', to='inventory.useritem')),
            ],
            options={
                'unique_together': {('lost_item', 'found_item')},
            },
        ),
    ]
